# Generated by Django 2.2.4 on 2019-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('price', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('shopNick', models.CharField(max_length=200)),
                ('payNum', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
